apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.csiDriverName }}
  labels:
    {{- include "qnap-csi.labels" . | nindent 4 }}
spec:
  attachRequired: false
  volumeLifecycleModes:
    - Persistent
